[build]
  command = "hugo"
  publish = "public"

[context.production]
  command = "hugo --baseURL https://kosli.com/secure-sdlc-process-template/"

[context.deploy-preview]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"